import gzip

from conftest import gfile

from moonraker_contrast.detect import detect_slicer, read_regions
from moonraker_contrast.extract import cast_value, parse_config_lines
from moonraker_contrast.parsers import get_parser_for


def _parse(filename):
    header, footer = read_regions(gfile(filename))
    slicer_info = detect_slicer(header, footer)
    return get_parser_for(slicer_info).parse(header, footer)


def test_prusa_block_extracted():
    result = _parse("prusa_footer.gcode")
    assert result.partial is False
    settings = result.settings
    assert settings["layer_height"] == 0.2
    assert settings["perimeters"] == 3
    assert settings["fill_density"] == "20%"        # percent kept as string
    assert settings["prusa_only_setting"] == "hello"
    # The "generated by" line is above the block and must be excluded.
    assert "generated" not in settings


def test_orca_block_with_config_block_markers():
    result = _parse("orca_footer.gcode")
    assert result.partial is False
    assert result.settings["wall_loops"] == 3
    assert result.settings["sparse_infill_density"] == "20%"


def test_bambu_markerless_header_scan():
    result = _parse("bambu_header.gcode")
    # No begin/end markers -> whole header scanned, but G-code lines ignored.
    assert result.settings["layer_height"] == 0.28
    assert result.settings["xy_contour_compensation"] == -0.2
    assert "M104" not in result.settings


def test_cast_value_types():
    assert cast_value("0.2") == 0.2
    assert cast_value("3") == 3
    assert cast_value("-0.2") == -0.2
    assert cast_value("1e-6") == 1e-6
    assert cast_value("20%") == "20%"        # percent stays string
    assert cast_value("PLA") == "PLA"
    assert cast_value("") is None
    assert cast_value("0,0.4,0.4") == "0,0.4,0.4"  # comma list kept raw


def test_ignore_keys_dropped():
    region = "; thumbnail = AAAA\n; layer_height = 0.2\n"
    settings = parse_config_lines(region, ignore_keys={"thumbnail"})
    assert "thumbnail" not in settings
    assert settings["layer_height"] == 0.2


def test_truncated_block_marks_partial():
    # begin marker present, end marker missing -> partial fallback.
    region = "; prusaslicer_config = begin\n; layer_height = 0.2\n"
    from moonraker_contrast.parsers.prusa import PrusaSlicerParser
    from moonraker_contrast.detect import SlicerInfo

    parser = PrusaSlicerParser(SlicerInfo("prusa", "PrusaSlicer", "x", "footer"))
    result = parser.parse("", region)
    assert result.partial is True
    assert result.settings["layer_height"] == 0.2


def test_gzip_roundtrip(tmp_path):
    raw_bytes = gfile("prusa_footer.gcode").read_bytes()
    gzip_path = tmp_path / "p.gcode.gz"
    with gzip.open(gzip_path, "wb") as file_handle:
        file_handle.write(raw_bytes)
    header, footer = read_regions(gzip_path)
    slicer_info = detect_slicer(header, footer)
    assert slicer_info.name == "PrusaSlicer"
    result = get_parser_for(slicer_info).parse(header, footer)
    assert result.settings["layer_height"] == 0.2
