; generated by OrcaSlicer 2.1.0 on 2024-02-02 at 10:00:00
G28
G1 Z5 F5000
; CONFIG_BLOCK_START
; layer_height = 0.2
; initial_layer_print_height = 0.2
; sparse_infill_density = 20%
; wall_loops = 3
; elefant_foot_compensation = 0.2
; enable_support = 0
; spiral_mode = 0
; brim_object_gap = 0.1
; top_shell_layers = 5
; bottom_shell_layers = 4
; nozzle_diameter = 0.4
; orca_only_setting = world
; CONFIG_BLOCK_END
