; generated by PrusaSlicer 2.7.1+linux-x64 on 2024-01-01 at 12:00:00 UTC
M73 P0 R10
G28 ; home all
G1 Z5 F5000
; filament used [mm] = 1234.5
;
; prusaslicer_config = begin
; layer_height = 0.2
; first_layer_height = 0.2
; fill_density = 20%
; perimeters = 3
; elefant_foot_compensation = 0.2
; support_material = 0
; spiral_vase = 0
; brim_separation = 0.1
; top_solid_layers = 5
; bottom_solid_layers = 4
; nozzle_diameter = 0.4
; prusa_only_setting = hello
; prusaslicer_config = end
