"""Self-contained slicer detection.

We deliberately do NOT rely on Moonraker having pre-parsed a file's metadata.
Instead we read the same regions Moonraker would (the first and last 1 MiB) and
identify the slicer from its own header/footer markers, mirroring the patterns
in ``moonraker/components/file_manager/metadata.py``.

Cura is intentionally absent from the detection table: it does not embed its
full settings in the gcode by default, so it cannot be compared.
"""

from __future__ import annotations

import gzip
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Tuple

#: Match Moonraker's read window so footer/header offsets line up exactly.
READ_SIZE = 1024 * 1024  # 1 MiB

#: ``; generated by <Name> <version> on <YYYY-MM-DD> at <HH:MM:SS>``
#: This is emitted by PrusaSlicer and every fork built on the slic3r engine.
_GENERATED_BY_RE = re.compile(
    r"; generated by (.+?) on \d{4}-\d{2}-\d{2} at \d{2}:\d{2}:\d{2}"
)

#: Fallback used when the dated "generated by" line is absent (older exports).
_PRUSA_FAMILY_ALIASES = [
    "PrusaSlicer", "SuperSlicer", "OrcaSlicer", "MomentSlicer",
    "SliCR-3D", "A3dp-Slicer", "QIDISlicer",
]
_PRUSA_FALLBACK_RE = re.compile(
    rf"({'|'.join(_PRUSA_FAMILY_ALIASES)})\s(.*?)\son"
)

#: BambuStudio (and the older BambuSlicer) tag the header with their name.
#: e.g. ``; BambuStudio 1.9.0`` / ``; BambuStudio_1.9.0`` / ``; BambuSlicer 1.0``
_BAMBU_RE = re.compile(r"; Bambu(?:Studio|Slicer)[^ ]* ([^\n]+)")


@dataclass
class SlicerInfo:
    """Everything the parser layer needs to read a file's config block.

    family: which config-block convention to use ("prusa" or "bambu").
    name: the human slicer name reported in the diff output.
    version: the slicer version string (best-effort; may be "").
    config_location: where the settings block lives ("footer" or "header").
    """

    family: str
    name: str
    version: str
    config_location: str


def _open_maybe_gz(path: Path):
    """Open ``path`` for binary reading, transparently handling gzip.

    Returns a tuple ``(file_obj, is_gzip)``. Callers must close ``file_obj``.
    """
    with open(path, "rb") as probe_file:
        magic_bytes = probe_file.read(2)
    if magic_bytes == b"\x1f\x8b":
        return gzip.open(path, "rb"), True
    return open(path, "rb"), False


def read_regions(path: Path) -> Tuple[str, str]:
    """Return ``(header, footer)`` text, each up to READ_SIZE bytes.

    For plain files we seek directly to the tail (cheap). For gzip we cannot
    seek from the end, so we stream-decompress while keeping only a rolling
    window of the last READ_SIZE bytes, bounding memory to ~2 MiB regardless
    of decompressed size.
    """
    path = Path(path)
    file_obj, is_gzip = _open_maybe_gz(path)
    try:
        if not is_gzip:
            header_bytes = file_obj.read(READ_SIZE)
            file_size = file_obj.seek(0, os.SEEK_END)
            if file_size <= READ_SIZE:
                footer_bytes = header_bytes
            else:
                file_obj.seek(max(0, file_size - READ_SIZE))
                footer_bytes = file_obj.read()
        else:
            header_bytes = file_obj.read(READ_SIZE)
            rolling_tail = bytearray(header_bytes)
            while True:
                chunk = file_obj.read(READ_SIZE)
                if not chunk:
                    break
                rolling_tail.extend(chunk)
                if len(rolling_tail) > READ_SIZE:
                    del rolling_tail[:-READ_SIZE]
            footer_bytes = bytes(rolling_tail)
    finally:
        file_obj.close()
    return (
        header_bytes.decode(errors="ignore"),
        footer_bytes.decode(errors="ignore"),
    )


def detect_slicer(header: str, footer: str) -> Optional[SlicerInfo]:
    """Identify the slicer from header/footer text.

    Precedence matters: BambuStudio is checked first because its header marker
    is specific, and the generic slic3r "generated by" line could otherwise
    mis-handle it. Returns ``None`` when no supported slicer is recognized.
    """
    combined_text = header + "\n" + footer

    # 1) BambuStudio / BambuSlicer -- settings live in the header.
    bambu_match = _BAMBU_RE.search(combined_text)
    if bambu_match is not None:
        matched_text = bambu_match.group(0)
        name = "BambuSlicer" if "BambuSlicer" in matched_text else "BambuStudio"
        return SlicerInfo(
            family="bambu",
            name=name,
            version=bambu_match.group(1).strip(),
            config_location="header",
        )

    # 2) PrusaSlicer and forks -- settings live in the footer.
    generated_by_match = _GENERATED_BY_RE.search(combined_text)
    if generated_by_match is not None:
        name, _, version = generated_by_match.group(1).rpartition(" ")
        if not name:  # no space -> whole string is the name
            name, version = version, ""
        return SlicerInfo(
            family="prusa",
            name=name,
            version=version,
            config_location="footer",
        )

    # 3) Legacy fallback for the slic3r family.
    fallback_match = _PRUSA_FALLBACK_RE.search(combined_text)
    if fallback_match is not None:
        return SlicerInfo(
            family="prusa",
            name=fallback_match.group(1),
            version=fallback_match.group(2).strip(),
            config_location="footer",
        )

    return None
